- name: nginx up to date
  become: true
  apt:
    name: nginx
    state: latest

- name: base nginx config
  become: true
  copy:
    src: "{{ role_path }}/files/nginx.conf"
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify:
    - restart nginx

- name: render configs
  become: true
  copy:
    src: "{{item.value.file_location}}/{{item.value.file_name}}"
    dest: "/etc/nginx/sites-available/{{item.value.file_name}}"
    mode: 0644
  with_dict: "{{ nginx_configs }}"

- name: link configs
  become: true
  file:
    src: "/etc/nginx/sites-available/{{item.value.file_name}}"
    dest: "/etc/nginx/sites-enabled/{{item.value.file_name}}"
    state: link
  with_dict: "{{ nginx_configs }}"
  notify:
    - restart nginx

