- name: Ensure augmenture installed
  become: yes
  npm:
    name: augmenture
    global: yes
    state: latest
    version: latest

- name: Generate systemd service
  become: yes
  template:
    src: templates/augmenture.service.j2
    dest: /lib/systemd/system/augmenture.service
  notify: start augmenture

- name: Generate nginx configuration
  become: yes
  template:
    src: ./templates/augmenture.conf.j2
    dest: /etc/nginx/sites-available/augmenture.conf

- name: Enable nginx configuration
  become: yes
  file:
    state: link
    src: /etc/nginx/sites-available/augmenture.conf
    path: /etc/nginx/sites-enabled/80-augmenture.conf
  notify: restart nginx
