- name: Ensure augmenture installed
  become: yes
  npm:
    name: augmenture
    global: yes
    state: latest

- name: Generate systemd service
  become: yes
  template:
    src: templates/augmenture.service.j2
    dest: /lib/systemd/system/augmenture.service
  notify: start augmenture
