- name: Ensure software-properties-common installed
  apt:
    name: software-properties-common

- name: Add docker repo gpg key
  command: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

- name: Add docker apt repo
  become: true
  command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

- name: Ensure docker is installed
  become: true
  apt:
    name: docker-ce
    update_cache: yes
